name: Revisar Código JS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar ESLint
        run: npx eslint . --ext .js
