name: Revisar HTML, CSS y JS

on:
  push:
    branches: [main]

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar linters
      run: |
        npm install -g htmlhint stylelint eslint

    - name: Revisar HTML
      run: |
        htmlhint "**/*.html"

    - name: Revisar CSS
      run: |
        stylelint "**/*.css"

    - name: Revisar JS
      run: |
        eslint "**/*.js"
