# .github/workflows/html-linter.yml
name: Verificación HTML/CSS/JS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código
      uses: actions/checkout@v3

    - name: Validar HTML con htmlhint
      uses: xt0rted/htmlhint-action@v1
      with:
        files: '**/*.html'

    - name: Validar CSS con stylelint
      uses: reviewdog/action-stylelint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
